### ISSUE TITLE
Edits to md

### ISSUE THREAD

**Issue by jhollist** [tim-salabim/rspatial#2]
@tim-salabim Should we use pull requests for edits or direct edit and push?

Thanks for setting this up and including me!  I'm more than a bit humbled to be included in such good company!

**Comment by bhaskarvk** [comment]
I vote for PR. PRs are very good for collaboration.

**Comment by tim-salabim** [comment]
I am happy with both.

**Comment by jhollist** [comment]
Closing this as PRs seems to be preference.
